version: '3'

services:
  head:
    image: mobz/elasticsearch-head:5
    ports:
      - "9100:9100"
    deploy:
      placement:
        constraints: [node.Role == manager]
  viz:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints: [node.Role == manager]
  master:
    image: itzg/elasticsearch:5
    environment:
      PLUGINS: ingest-attachment
      TYPE: MASTER
      UNICAST_HOSTS: master
      MIN_MASTERS: 1
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
  data:
    image: itzg/elasticsearch:5
    environment:
      PLUGINS: ingest-attachment
      TYPE: DATA
      UNICAST_HOSTS: master
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 60s
  gateway:
    image: itzg/elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch-5.4.2/config/elasticsearch.yml
    environment:
      PLUGINS: ingest-attachment
      TYPE: GATEWAY
      UNICAST_HOSTS: master
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
  ingest:
    image: itzg/elasticsearch:5
    ports:
      - "9222:9200"
    environment:
      PLUGINS: ingest-attachment
      TYPE: INGEST
      UNICAST_HOSTS: master
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"      
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://gateway:9200
